files:
  - inputFile: "input/Hz.Omer.S01E01.srt"
    outputFile: "output/Hz.Omer.S01E01.srt"
    offset: -1m
  - inputFile: "input/Hz.Omer.S01E24.srt"
    outputFile: "output/Hz.Omer.S01E24.srt"
    offset: -5s
  - inputFile: "input/Hz.Omer.S01E25.srt"
    outputFile: "output/Hz.Omer.S01E25.srt"
    offset: -4s
